version: '3'
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    ports:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      - database
volumes:
  data: